name: 'Terragrunt'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform Actions'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Format'
        uses: jacekhewko/terraform-github-actions@terragrunt
        with:
          tf_actions_version: 0.12.13
          tg_actions_version: 0.21.6
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS }}
      - name: 'Init'
        uses: jacekhewko/terraform-github-actions@terragrunt
        with:
          tf_actions_version: 0.12.13
          tg_actions_version: 0.21.6
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS }}
      - name: 'Validate'
        uses: jacekhewko/terraform-github-actions@terragrunt
        with:
          tf_actions_version: 0.12.13
          tg_actions_version: 0.21.6
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS }}
